#!/bin/sh
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151226.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151219.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151212.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151205.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151128.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151121.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151114.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151107.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151031.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151024.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151017.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151010.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_151003.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150926.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150919.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150912.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150905.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150829.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150822.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150815.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150808.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150801.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150725.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150718.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150711.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150704.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150627.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150620.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150613.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150606.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150530.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150523.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150516.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150509.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150502.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150425.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150418.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150411.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150404.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150328.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150321.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150314.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150307.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150228.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150221.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150214.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150207.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150131.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150124.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150117.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150110.txt
wget http://web.mta.info/developers/data/nyct/turnstile/turnstile_150103.txt
